apiVersion: apps/v1
kind: Deployment
metadata:
  name: chevereto-free-https
  namespace: chevereto-free
  labels:
    app: chevereto-free
    tier: https-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chevereto-free
      tier: https-app
  template:
    metadata:
      labels:
        app: chevereto-free
        tier: https-app
    spec:
      containers:
        - name: cheveretofreehttps
          image: chevereto-free-https:v1
          env:
            - name: CHEVERETO_TAG
              value: dev
            - name: CHEVERETO_DB_HOST
              value: chevereto-free-https-mysql
            - name: CHEVERETO_DB_USER
              value: chevereto
            - name: CHEVERETO_DB_PASS
              value: tata
            - name: CHEVERETO_DB_PORT
              value: "3306"
            - name: CHEVERETO_DB_NAME
              value: chevereto
            - name: CHEVERETO_DISABLE_UPDATE_HTTP
              value: "1"
            - name: CHEVERETO_DISABLE_UPDATE_CLI
              value: "1"
            - name: CHEVERETO_HTTPS
              value: "1"
            - name: CHEVERETO_DEBUG_LEVEL
              value: "2"
          volumeMounts:
            - name: chevereto-free-https-config
              mountPath: /config
            - name: chevereto-free-https-data
              mountPath: /data
            # This is for the openssl certificate you generated while thoroughly following CONTRIBUTING.md
            - name: ssl-certificate
              mountPath: /etc/apache2/ssl/ssl.crt
            - name: ssl-certificate-key
              mountPath: /etc/apache2/ssl/ssl.key
            # for HTTPS, /etc/apache2/sites-enabled/000-default.conf must be overriden
            - name: apache-config
              mountPath: /etc/apache2/sites-enabled/000-default.conf
      volumes:
        - name: chevereto-free-https-config
          persistentVolumeClaim:
            claimName: chevereto-free-https-config
        - name: chevereto-free-https-data
          persistentVolumeClaim:
            claimName: chevereto-free-https-data
          # Make sure you generated those 3 files as described in /CONTRIBUTING.md !
        - name: ssl-certificate
          hostPath:
            path: ~/cheveretoConfig/ssl.crt
            type: FileOrCreate
        - name: ssl-certificate-key
          hostPath:
            path: ~/cheveretoConfig/ssl.key
            type: FileOrCreate
        - name: apache-config
          hostPath:
            path: ~/cheveretoConfig/000-default.conf
            type: FileOrCreate
