apiVersion: v1
kind: Service
metadata:
  name: chevereto-free-http
  namespace: chevereto-free
  labels:
    app: chevereto-free
    tier: http-app
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: chevereto-free
    tier: http-app
