apiVersion: v1
kind: Service
metadata:
  name: chevereto-free-https-mysql
  namespace: chevereto-free
  labels:
    app: chevereto-free
    tier: https-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: chevereto-free
    tier: https-mysql
