apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chevereto-free-http-mysql-data
  namespace: chevereto-free
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
