name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - dev
      - feat-*
      - fix-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set the Node version specified in .nvmrc
        shell: bash -l {0}
        run: nvm install

      - name: Install dependencies
        run: npm ci

      - name: Build imgbb-uploader
        run: npm run build

      - name: Run test suites defined in src/__tests__/**
        env:
          API_KEY: ${{ secrets.IMGBB_API_KEY }}
          CHEVERETO_HTTP_HOST: ${{ secrets.CHEVERETO_HTTP_HOST }}
          CHEVERETO_HTTP_API_KEY: ${{ secrets.CHEVERETO_HTTP_API_KEY }}
          CHEVERETO_HTTPS_HOST: ${{ secrets.CHEVERETO_HTTPS_HOST }}
          CHEVERETO_HTTPS_API_KEY: ${{ secrets.CHEVERETO_HTTPS_API_KEY }}
        run: npm run test
